export const LIST_CITY = [
  { value: 1, label: "Hà Nội", postcode: 100000 },
  { value: 2, label: "Hải Phòng", postcode: 180000 },
  { value: 3, label: "Bắc Giang", postcode: 220000 },
  { value: 6, label: "Cao Bằng", postcode: 270000 },
  { value: 4, label: "Bắc Kạn", postcode: 960000 },
  { value: 8, label: "Hòa Bình", postcode: 350000 },
  { value: 9, label: "Hải Dương", postcode: 170000 },
  { value: 5, label: "Bắc Ninh", postcode: 790000 },
  { value: 11, label: "Hà Nam", postcode: 400000 },
  { value: 12, label: "Hưng Yên", postcode: 160000 },
  { value: 13, label: "Lào Cai", postcode: 330000 },
  { value: 14, label: "Lai Châu", postcode: 390000 },
  { value: 15, label: "Lạng Sơn", postcode: 240000 },
  { value: 16, label: "Ninh Bình", postcode: 430000 },
  { value: 17, label: "Nam Định", postcode: 420000 },
  { value: 18, label: "Phú Thọ", postcode: 290000 },
  { value: 19, label: "Quảng Ninh", postcode: 200000 },
  { value: 20, label: "Sơn La", postcode: 360000 },
  { value: 21, label: "Thái Bình", postcode: 410000 },
  { value: 22, label: "Thái Nguyên", postcode: 250000 },
  { value: 23, label: "Tuyên Quang", postcode: 300000 },
  { value: 24, label: "Vĩnh Phúc", postcode: 280000 },
  { value: 7, label: "Điện Biên", postcode: 380000 },
  { value: 26, label: "Đà Nẵng", postcode: 550000 },
  { value: 27, label: "Thừa Thiên Huế", postcode: 530000 },
  { value: 28, label: "Khánh Hòa", postcode: 650000 },
  { value: 29, label: "Lâm Đồng", postcode: 670000 },
  { value: 31, label: "Bình Thuận", postcode: 800000 },
  { value: 10, label: "Hà Giang", postcode: 310000 },
  { value: 32, label: "Đắk Lắk", postcode: 630000 },
  { value: 33, label: "Đắk Nông", postcode: 640000 },
  { value: 34, label: "Gia Lai", postcode: 600000 },
  { value: 35, label: "Hà Tĩnh", postcode: 480000 },
  { value: 36, label: "Kon Tum", postcode: 580000 },
  { value: 37, label: "Nghệ An", postcode: 460000 - 470000 },
  { value: 38, label: "Ninh Thuận", postcode: 660000 },
  { value: 39, label: "Phú Yên", postcode: 620000 },
  { value: 40, label: "Quảng Bình", postcode: 510000 },
  { value: 41, label: "Quảng Nam", postcode: 560000 },
  { value: 42, label: "Quảng Ngãi", postcode: 570000 },
  { value: 43, label: "Quảng Trị", postcode: 520000 },
  { value: 44, label: "Thanh Hóa", postcode: 440000 - 450000 },
  { value: 45, label: "Hồ Chí Minh", postcode: 700000 },
  { value: 46, label: "Bình Dương", postcode: 590000 },
  { value: 47, label: "Bà Rịa Vũng Tàu", postcode: 790000 },
  { value: 25, label: "Yên Bái", postcode: 320000 },
  { value: 30, label: "Bình Định", postcode: 820000 },
  { value: 50, label: "Bạc Liêu", postcode: 260000 },
  { value: 51, label: "Bình Phước", postcode: 830000 },
  { value: 52, label: "Bến Tre", postcode: 930000 },
  { value: 53, label: "Cà Mau", postcode: 970000 },
  { value: 54, label: "Đồng Tháp", postcode: 870000 },
  { value: 55, label: "Đồng Nai", postcode: 810000 },
  { value: 56, label: "Hậu Giang", postcode: 910000 },
  { value: 57, label: "Kiên Giang", postcode: 920000 },
  { value: 58, label: "Long An", postcode: 850000 },
  { value: 59, label: "Sóc Trăng", postcode: 950000 },
  { value: 60, label: "Tiền Giang", postcode: 860000 },
  { value: 61, label: "Tây Ninh", postcode: 840000 },
  { value: 62, label: "Trà Vinh", postcode: 940000 },
  { value: 63, label: "Vĩnh Long", postcode: 890000 },
  { value: 48, label: "Cần Thơ", postcode: 900000 },
  { value: 49, label: "An Giang", postcode: 880000 },
];
export const renderCity = (id: any) => {
  const option = {
    1: "Hà Nội ",
    2: "Hải Phòng ",
    3: "Bắc Giang ",
    6: "Cao Bằng ",
    4: "Bắc Kạn ",
    8: "Hòa Bình ",
    9: "Hải Dương ",
    5: "Bắc Ninh ",
    11: "Hà Nam ",
    12: "Hưng Yên ",
    13: "Lào Cai ",
    14: "Lai Châu ",
    15: "Lạng Sơn ",
    16: "Ninh Bình ",
    17: "Nam Định ",
    18: "Phú Thọ ",
    19: "Quảng Ninh ",
    20: "Sơn La ",
    21: "Thái Bình ",
    22: "Thái Nguyên ",
    23: "Tuyên Quang ",
    24: "Vĩnh Phúc ",
    7: "Điện Biên ",
    26: "Đà Nẵng ",
    27: "Thừa Thiên Huế ",
    28: "Khánh Hòa ",
    29: "Lâm Đồng ",
    31: "Bình Thuận ",
    10: "Hà Giang ",
    32: "Đắk Lắk ",
    33: "Đắk Nông ",
    34: "Gia Lai ",
    35: "Hà Tĩnh ",
    36: "Kon Tum ",
    37: "Nghệ An ",
    38: "Ninh Thuận ",
    39: "Phú Yên ",
    40: "Quảng Bình ",
    41: "Quảng Nam ",
    42: "Quảng Ngãi ",
    43: "Quảng Trị ",
    44: "Thanh Hóa ",
    45: "Hồ Chí Minh ",
    46: "Bình Dương ",
    47: "Bà Rịa Vũng Tàu ",
    25: "Yên Bái ",
    30: "Bình Định ",
    50: "Bạc Liêu ",
    51: "Bình Phước ",
    52: "Bến Tre ",
    53: "Cà Mau ",
    54: "Đồng Tháp ",
    55: "Đồng Nai ",
    56: "Hậu Giang ",
    57: "Kiên Giang ",
    58: "Long An ",
    59: "Sóc Trăng ",
    60: "Tiền Giang ",
    61: "Tây Ninh ",
    62: "Trà Vinh ",
    63: "Vĩnh Long ",
    48: "Cần Thơ ",
    49: "An Giang ",
  };
  if (!option[id]) {
    return "Không có dữ liệu";
  }
  return option[id];
};
export const LIST_DISTRICT = [
  { value: 66, label: "Quận Ba Đình", parent: 1 },
  { value: 67, label: "Quận Hoàn Kiếm", parent: 1 },
  { value: 68, label: "Quận Tây Hồ", parent: 1 },
  { value: 69, label: "Quận Long Biên", parent: 1 },
  { value: 70, label: "Quận Cầu Giấy", parent: 1 },
  { value: 71, label: "Quận Đống Đa", parent: 1 },
  { value: 72, label: "Quận Hai Bà Trưng", parent: 1 },
  { value: 73, label: "Quận Hoàng Mai", parent: 1 },
  { value: 74, label: "Quận Thanh Xuân", parent: 1 },
  { value: 75, label: "Huyện Sóc Sơn", parent: 1 },
  { value: 76, label: "Huyện Đông Anh", parent: 1 },
  { value: 77, label: "Huyện Gia Lâm", parent: 1 },
  { value: 78, label: "Quận Nam Từ Liêm", parent: 1 },
  { value: 79, label: "Huyện Thanh Trì", parent: 1 },
  { value: 80, label: "Quận Bắc Từ Liêm", parent: 1 },
  { value: 81, label: "Huyện Mê Linh", parent: 1 },
  { value: 82, label: "Quận Hà Đông", parent: 1 },
  { value: 83, label: "Thị xã Sơn Tây", parent: 1 },
  { value: 84, label: "Huyện Ba Vì", parent: 1 },
  { value: 85, label: "Huyện Phúc Thọ", parent: 1 },
  { value: 86, label: "Huyện Đan Phượng", parent: 1 },
  { value: 87, label: "Huyện Hoài Đức", parent: 1 },
  { value: 89, label: "Huyện Thạch Thất", parent: 1 },
  { value: 90, label: "Huyện Chương Mỹ", parent: 1 },
  { value: 91, label: "Huyện Thanh Oai", parent: 1 },
  { value: 92, label: "Huyện Thường Tín", parent: 1 },
  { value: 93, label: "Huyện Phú Xuyên", parent: 1 },
  { value: 94, label: "Huyện Ứng Hòa", parent: 1 },
  { value: 95, label: "Huyện Mỹ Đức", parent: 1 },
  { value: 96, label: "Thành phố Hà Giang", parent: 10 },
  { value: 97, label: "Huyện Đồng Văn", parent: 10 },
  { value: 98, label: "Huyện Mèo Vạc", parent: 10 },
  { value: 99, label: "Huyện Yên Minh", parent: 10 },
  { value: 100, label: "Huyện Quản Bạ", parent: 10 },
  { value: 101, label: "Huyện Vị Xuyên", parent: 10 },
  { value: 102, label: "Huyện Bắc Mê", parent: 10 },
  { value: 103, label: "Huyện Hoàng Su Phì", parent: 10 },
  { value: 104, label: "Huyện Xín Mần", parent: 10 },
  { value: 105, label: "Huyện Bắc Quang", parent: 10 },
  { value: 106, label: "Huyện Quang Bình", parent: 10 },
  { value: 107, label: "Thành phố Cao Bằng", parent: 6 },
  { value: 108, label: "Huyện Bảo Lâm", parent: 6 },
  { value: 109, label: "Huyện Bảo Lạc", parent: 6 },
  { value: 110, label: "Huyện Thông Nông", parent: 6 },
  { value: 111, label: "Huyện Hà Quảng", parent: 6 },
  { value: 112, label: "Huyện Trà Lĩnh", parent: 6 },
  { value: 113, label: "Huyện Trùng Khánh", parent: 6 },
  { value: 114, label: "Huyện Hạ Lang", parent: 6 },
  { value: 115, label: "Huyện Quảng Uyên", parent: 6 },
  { value: 116, label: "Huyện Phục Hoà", parent: 6 },
  { value: 117, label: "Huyện Hoà An", parent: 6 },
  { value: 118, label: "Huyện Nguyên Bình", parent: 6 },
  { value: 119, label: "Huyện Thạch An", parent: 6 },
  { value: 120, label: "Thành Phố Bắc Kạn", parent: 4 },
  { value: 121, label: "Huyện Pác Nặm", parent: 4 },
  { value: 122, label: "Huyện Ba Bể", parent: 4 },
  { value: 123, label: "Huyện Ngân Sơn", parent: 4 },
  { value: 124, label: "Huyện Bạch Thông", parent: 4 },
  { value: 125, label: "Huyện Chợ Đồn", parent: 4 },
  { value: 126, label: "Huyện Chợ Mới", parent: 4 },
  { value: 127, label: "Huyện Na Rì", parent: 4 },
  { value: 128, label: "Thành phố Tuyên Quang", parent: 23 },
  { value: 129, label: "Huyện Lâm Bình", parent: 23 },
  { value: 130, label: "Huyện Nà Hang", parent: 23 },
  { value: 131, label: "Huyện Chiêm Hóa", parent: 23 },
  { value: 132, label: "Huyện Hàm Yên", parent: 23 },
  { value: 133, label: "Huyện Yên Sơn", parent: 23 },
  { value: 134, label: "Huyện Sơn Dương", parent: 23 },
  { value: 135, label: "Thành phố Lào Cai", parent: 13 },
  { value: 136, label: "Huyện Bát Xát", parent: 13 },
  { value: 138, label: "Huyện Si Ma Cai", parent: 13 },
  { value: 139, label: "Huyện Bắc Hà", parent: 13 },
  { value: 140, label: "Huyện Bảo Thắng", parent: 13 },
  { value: 141, label: "Huyện Bảo Yên", parent: 13 },
  { value: 142, label: "Thị xã Sa Pa", parent: 13 },
  { value: 143, label: "Huyện Văn Bàn", parent: 13 },
  { value: 144, label: "Thành phố Điện Biên Phủ", parent: 7 },
  { value: 145, label: "Thị Xã Mường Lay", parent: 7 },
  { value: 146, label: "Huyện Mường Nhé", parent: 7 },
  { value: 147, label: "Huyện Mường Chà", parent: 7 },
  { value: 148, label: "Huyện Tủa Chùa", parent: 7 },
  { value: 149, label: "Huyện Tuần Giáo", parent: 7 },
  { value: 150, label: "Huyện Điện Biên", parent: 7 },
  { value: 151, label: "Huyện Điện Biên Đông", parent: 7 },
  { value: 152, label: "Huyện Mường Ảng", parent: 7 },
  { value: 153, label: "Huyện Nậm Pồ", parent: 7 },
  { value: 154, label: "Thành phố Lai Châu", parent: 14 },
  { value: 155, label: "Huyện Tam Đường", parent: 14 },
  { value: 156, label: "Huyện Mường Tè", parent: 14 },
  { value: 157, label: "Huyện Sìn Hồ", parent: 14 },
  { value: 158, label: "Huyện Phong Thổ", parent: 14 },
  { value: 159, label: "Huyện Than Uyên", parent: 14 },
  { value: 160, label: "Huyện Tân Uyên", parent: 14 },
  { value: 161, label: "Huyện Nậm Nhùn", parent: 14 },
  { value: 162, label: "Thành phố Sơn La", parent: 20 },
  { value: 88, label: "Huyện Quốc Oai", parent: 1 },
  { value: 164, label: "Huyện Thuận Châu", parent: 20 },
  { value: 165, label: "Huyện Mường La", parent: 20 },
  { value: 166, label: "Huyện Bắc Yên", parent: 20 },
  { value: 167, label: "Huyện Phù Yên", parent: 20 },
  { value: 168, label: "Huyện Mộc Châu", parent: 20 },
  { value: 169, label: "Huyện Yên Châu", parent: 20 },
  { value: 170, label: "Huyện Mai Sơn", parent: 20 },
  { value: 171, label: "Huyện Sông Mã", parent: 20 },
  { value: 172, label: "Huyện Sốp Cộp", parent: 20 },
  { value: 173, label: "Huyện Vân Hồ", parent: 20 },
  { value: 174, label: "Thành phố Yên Bái", parent: 25 },
  { value: 175, label: "Thị xã Nghĩa Lộ", parent: 25 },
  { value: 176, label: "Huyện Lục Yên", parent: 25 },
  { value: 177, label: "Huyện Văn Yên", parent: 25 },
  { value: 178, label: "Huyện Mù Căng Chải", parent: 25 },
  { value: 179, label: "Huyện Trấn Yên", parent: 25 },
  { value: 180, label: "Huyện Trạm Tấu", parent: 25 },
  { value: 181, label: "Huyện Văn Chấn", parent: 25 },
  { value: 182, label: "Huyện Yên Bình", parent: 25 },
  { value: 183, label: "Thành phố Hòa Bình", parent: 8 },
  { value: 184, label: "Huyện Đà Bắc", parent: 8 },
  { value: 185, label: "Huyện Kỳ Sơn", parent: 8 },
  { value: 186, label: "Huyện Lương Sơn", parent: 8 },
  { value: 187, label: "Huyện Kim Bôi", parent: 8 },
  { value: 188, label: "Huyện Cao Phong", parent: 8 },
  { value: 189, label: "Huyện Tân Lạc", parent: 8 },
  { value: 190, label: "Huyện Mai Châu", parent: 8 },
  { value: 191, label: "Huyện Lạc Sơn", parent: 8 },
  { value: 192, label: "Huyện Yên Thủy", parent: 8 },
  { value: 193, label: "Huyện Lạc Thủy", parent: 8 },
  { value: 194, label: "Thành phố Thái Nguyên", parent: 22 },
  { value: 195, label: "Thành phố Sông Công", parent: 22 },
  { value: 196, label: "Huyện Định Hóa", parent: 22 },
  { value: 197, label: "Huyện Phú Lương", parent: 22 },
  { value: 198, label: "Huyện Đồng Hỷ", parent: 22 },
  { value: 199, label: "Huyện Võ Nhai", parent: 22 },
  { value: 200, label: "Huyện Đại Từ", parent: 22 },
  { value: 201, label: "Thị xã Phổ Yên", parent: 22 },
  { value: 202, label: "Huyện Phú Bình", parent: 22 },
  { value: 203, label: "Thành phố Lạng Sơn", parent: 15 },
  { value: 204, label: "Huyện Tràng Định", parent: 15 },
  { value: 205, label: "Huyện Bình Gia", parent: 15 },
  { value: 206, label: "Huyện Văn Lãng", parent: 15 },
  { value: 207, label: "Huyện Cao Lộc", parent: 15 },
  { value: 208, label: "Huyện Văn Quan", parent: 15 },
  { value: 209, label: "Huyện Bắc Sơn", parent: 15 },
  { value: 210, label: "Huyện Hữu Lũng", parent: 15 },
  { value: 211, label: "Huyện Chi Lăng", parent: 15 },
  { value: 212, label: "Huyện Lộc Bình", parent: 15 },
  { value: 213, label: "Huyện Đình Lập", parent: 15 },
  { value: 214, label: "Thành phố Hạ Long", parent: 19 },
  { value: 215, label: "Thành phố Móng Cái", parent: 19 },
  { value: 137, label: "Huyện Mường Khương", parent: 13 },
  { value: 217, label: "Thành phố Uông Bí", parent: 19 },
  { value: 218, label: "Huyện Bình Liêu", parent: 19 },
  { value: 219, label: "Huyện Tiên Yên", parent: 19 },
  { value: 220, label: "Huyện Đầm Hà", parent: 19 },
  { value: 221, label: "Huyện Hải Hà", parent: 19 },
  { value: 222, label: "Huyện Ba Chẽ", parent: 19 },
  { value: 223, label: "Huyện Vân Đồn", parent: 19 },
  { value: 225, label: "Thị xã Đông Triều", parent: 19 },
  { value: 226, label: "Thị xã Quảng Yên", parent: 19 },
  { value: 227, label: "Huyện Cô Tô", parent: 19 },
  { value: 228, label: "Thành phố Bắc Giang", parent: 3 },
  { value: 229, label: "Huyện Yên Thế", parent: 3 },
  { value: 230, label: "Huyện Tân Yên", parent: 3 },
  { value: 231, label: "Huyện Lạng Giang", parent: 3 },
  { value: 232, label: "Huyện Lục Nam", parent: 3 },
  { value: 233, label: "Huyện Lục Ngạn", parent: 3 },
  { value: 234, label: "Huyện Sơn Động", parent: 3 },
  { value: 235, label: "Huyện Yên Dũng", parent: 3 },
  { value: 236, label: "Huyện Việt Yên", parent: 3 },
  { value: 237, label: "Huyện Hiệp Hòa", parent: 3 },
  { value: 238, label: "Thành phố Việt Trì", parent: 18 },
  { value: 239, label: "Thị xã Phú Thọ", parent: 18 },
  { value: 240, label: "Huyện Đoan Hùng", parent: 18 },
  { value: 241, label: "Huyện Hạ Hoà", parent: 18 },
  { value: 242, label: "Huyện Thanh Ba", parent: 18 },
  { value: 243, label: "Huyện Phù Ninh", parent: 18 },
  { value: 244, label: "Huyện Yên Lập", parent: 18 },
  { value: 163, label: "Huyện Quỳnh Nhai", parent: 20 },
  { value: 246, label: "Huyện Tam Nông", parent: 18 },
  { value: 247, label: "Huyện Lâm Thao", parent: 18 },
  { value: 248, label: "Huyện Thanh Sơn", parent: 18 },
  { value: 249, label: "Huyện Thanh Thuỷ", parent: 18 },
  { value: 250, label: "Huyện Tân Sơn", parent: 18 },
  { value: 251, label: "Thành phố Vĩnh Yên", parent: 24 },
  { value: 252, label: "Thành phố Phúc Yên", parent: 24 },
  { value: 253, label: "Huyện Lập Thạch", parent: 24 },
  { value: 254, label: "Huyện Tam Dương", parent: 24 },
  { value: 255, label: "Huyện Tam Đảo", parent: 24 },
  { value: 256, label: "Huyện Bình Xuyên", parent: 24 },
  { value: 257, label: "Huyện Yên Lạc", parent: 24 },
  { value: 258, label: "Huyện Vĩnh Tường", parent: 24 },
  { value: 259, label: "Huyện Sông Lô", parent: 24 },
  { value: 260, label: "Thành phố Bắc Ninh", parent: 5 },
  { value: 261, label: "Huyện Yên Phong", parent: 5 },
  { value: 262, label: "Huyện Quế Võ", parent: 5 },
  { value: 263, label: "Huyện Tiên Du", parent: 5 },
  { value: 264, label: "Thị xã Từ Sơn", parent: 5 },
  { value: 265, label: "Huyện Thuận Thành", parent: 5 },
  { value: 266, label: "Huyện Gia Bình", parent: 5 },
  { value: 267, label: "Huyện Lương Tài", parent: 5 },
  { value: 268, label: "Thành phố Hải Dương", parent: 9 },
  { value: 269, label: "Thành phố Chí Linh", parent: 9 },
  { value: 270, label: "Huyện Nam Sách", parent: 9 },
  { value: 271, label: "Huyện Kinh Môn", parent: 9 },
  { value: 272, label: "Huyện Kim Thành", parent: 9 },
  { value: 273, label: "Huyện Thanh Hà", parent: 9 },
  { value: 274, label: "Huyện Cẩm Giàng", parent: 9 },
  { value: 275, label: "Huyện Bình Giang", parent: 9 },
  { value: 276, label: "Huyện Gia Lộc", parent: 9 },
  { value: 277, label: "Huyện Tứ Kỳ", parent: 9 },
  { value: 278, label: "Huyện Ninh Giang", parent: 9 },
  { value: 279, label: "Huyện Thanh Miện", parent: 9 },
  { value: 280, label: "Quận Hồng Bàng", parent: 2 },
  { value: 281, label: "Quận Ngô Quyền", parent: 2 },
  { value: 282, label: "Quận Lê Chân", parent: 2 },
  { value: 283, label: "Quận Hải An", parent: 2 },
  { value: 284, label: "Quận Kiến An", parent: 2 },
  { value: 285, label: "Quận Đồ Sơn", parent: 2 },
  { value: 286, label: "Quận Dương Kinh", parent: 2 },
  { value: 287, label: "Huyện Thuỷ Nguyên", parent: 2 },
  { value: 288, label: "Huyện An Dương", parent: 2 },
  { value: 289, label: "Huyện An Lão", parent: 2 },
  { value: 290, label: "Huyện Kiến Thuỵ", parent: 2 },
  { value: 291, label: "Huyện Tiên Lãng", parent: 2 },
  { value: 292, label: "Huyện Vĩnh Bảo", parent: 2 },
  { value: 293, label: "Huyện Cát Hải", parent: 2 },
  { value: 294, label: "Thành phố Hưng Yên", parent: 12 },
  { value: 295, label: "Huyện Văn Lâm", parent: 12 },
  { value: 296, label: "Huyện Văn Giang", parent: 12 },
  { value: 297, label: "Huyện Yên Mỹ", parent: 12 },
  { value: 298, label: "Thị xã Mỹ Hào", parent: 12 },
  { value: 299, label: "Huyện Ân Thi", parent: 12 },
  { value: 300, label: "Huyện Khoái Châu", parent: 12 },
  { value: 301, label: "Huyện Kim Động", parent: 12 },
  { value: 216, label: "Thành phố Cẩm Phả", parent: 19 },
  { value: 303, label: "Huyện Phù Cừ", parent: 12 },
  { value: 304, label: "Thành phố Thái Bình", parent: 21 },
  { value: 305, label: "Huyện Quỳnh Phụ", parent: 21 },
  { value: 306, label: "Huyện Hưng Hà", parent: 21 },
  { value: 307, label: "Huyện Đông Hưng", parent: 21 },
  { value: 308, label: "Huyện Thái Thụy", parent: 21 },
  { value: 309, label: "Huyện Tiền Hải", parent: 21 },
  { value: 310, label: "Huyện Kiến Xương", parent: 21 },
  { value: 311, label: "Huyện Vũ Thư", parent: 21 },
  { value: 312, label: "Thành phố Phủ Lý", parent: 11 },
  { value: 313, label: "Thị xã Duy Tiên", parent: 11 },
  { value: 314, label: "Huyện Kim Bảng", parent: 11 },
  { value: 315, label: "Huyện Thanh Liêm", parent: 11 },
  { value: 316, label: "Huyện Bình Lục", parent: 11 },
  { value: 317, label: "Huyện Lý Nhân", parent: 11 },
  { value: 318, label: "Thành phố Nam Định", parent: 17 },
  { value: 319, label: "Huyện Mỹ Lộc", parent: 17 },
  { value: 320, label: "Huyện Vụ Bản", parent: 17 },
  { value: 321, label: "Huyện Ý Yên", parent: 17 },
  { value: 322, label: "Huyện Nghĩa Hưng", parent: 17 },
  { value: 323, label: "Huyện Nam Trực", parent: 17 },
  { value: 324, label: "Huyện Trực Ninh", parent: 17 },
  { value: 325, label: "Huyện Xuân Trường", parent: 17 },
  { value: 326, label: "Huyện Giao Thủy", parent: 17 },
  { value: 327, label: "Huyện Hải Hậu", parent: 17 },
  { value: 328, label: "Thành phố Ninh Bình", parent: 16 },
  { value: 329, label: "Thành phố Tam Điệp", parent: 16 },
  { value: 330, label: "Huyện Nho Quan", parent: 16 },
  { value: 331, label: "Huyện Gia Viễn", parent: 16 },
  { value: 245, label: "Huyện Cẩm Khê", parent: 18 },
  { value: 333, label: "Huyện Yên Khánh", parent: 16 },
  { value: 334, label: "Huyện Kim Sơn", parent: 16 },
  { value: 335, label: "Huyện Yên Mô", parent: 16 },
  { value: 336, label: "Thành phố Thanh Hóa", parent: 44 },
  { value: 337, label: "Thị xã Bỉm Sơn", parent: 44 },
  { value: 338, label: "Thành phố Sầm Sơn", parent: 44 },
  { value: 339, label: "Huyện Mường Lát", parent: 44 },
  { value: 340, label: "Huyện Quan Hóa", parent: 44 },
  { value: 341, label: "Huyện Bá Thước", parent: 44 },
  { value: 342, label: "Huyện Quan Sơn", parent: 44 },
  { value: 343, label: "Huyện Lang Chánh", parent: 44 },
  { value: 344, label: "Huyện Ngọc Lặc", parent: 44 },
  { value: 345, label: "Huyện Cẩm Thủy", parent: 44 },
  { value: 346, label: "Huyện Thạch Thành", parent: 44 },
  { value: 347, label: "Huyện Hà Trung", parent: 44 },
  { value: 348, label: "Huyện Vĩnh Lộc", parent: 44 },
  { value: 349, label: "Huyện Yên Định", parent: 44 },
  { value: 350, label: "Huyện Thọ Xuân", parent: 44 },
  { value: 351, label: "Huyện Thường Xuân", parent: 44 },
  { value: 352, label: "Huyện Triệu Sơn", parent: 44 },
  { value: 353, label: "Huyện Thiệu Hóa", parent: 44 },
  { value: 354, label: "Huyện Hoằng Hóa", parent: 44 },
  { value: 355, label: "Huyện Hậu Lộc", parent: 44 },
  { value: 356, label: "Huyện Nga Sơn", parent: 44 },
  { value: 357, label: "Huyện Như Xuân", parent: 44 },
  { value: 358, label: "Huyện Như Thanh", parent: 44 },
  { value: 359, label: "Huyện Nông Cống", parent: 44 },
  { value: 360, label: "Huyện Đông Sơn", parent: 44 },
  { value: 361, label: "Huyện Quảng Xương", parent: 44 },
  { value: 362, label: "Huyện Tĩnh Gia", parent: 44 },
  { value: 363, label: "Thành phố Vinh", parent: 37 },
  { value: 364, label: "Thị xã Cửa Lò", parent: 37 },
  { value: 365, label: "Thị xã Thái Hoà", parent: 37 },
  { value: 366, label: "Huyện Quế Phong", parent: 37 },
  { value: 367, label: "Huyện Quỳ Châu", parent: 37 },
  { value: 368, label: "Huyện Tương Dương", parent: 37 },
  { value: 369, label: "Huyện Nghĩa Đàn", parent: 37 },
  { value: 370, label: "Huyện Quỳ Hợp", parent: 37 },
  { value: 371, label: "Huyện Quỳnh Lưu", parent: 37 },
  { value: 372, label: "Huyện Con Cuông", parent: 37 },
  { value: 373, label: "Huyện Tân Kỳ", parent: 37 },
  { value: 374, label: "Huyện Anh Sơn", parent: 37 },
  { value: 375, label: "Huyện Diễn Châu", parent: 37 },
  { value: 376, label: "Huyện Yên Thành", parent: 37 },
  { value: 377, label: "Huyện Đô Lương", parent: 37 },
  { value: 378, label: "Huyện Thanh Chương", parent: 37 },
  { value: 379, label: "Huyện Nghi Lộc", parent: 37 },
  { value: 380, label: "Huyện Nam Đàn", parent: 37 },
  { value: 381, label: "Huyện Hưng Nguyên", parent: 37 },
  { value: 382, label: "Thị xã Hoàng Mai", parent: 37 },
  { value: 383, label: "Thành phố Hà Tĩnh", parent: 35 },
  { value: 384, label: "Thị xã Hồng Lĩnh", parent: 35 },
  { value: 385, label: "Huyện Hương Sơn", parent: 35 },
  { value: 386, label: "Huyện Đức Thọ", parent: 35 },
  { value: 387, label: "Huyện Vũ Quang", parent: 35 },
  { value: 388, label: "Huyện Nghi Xuân", parent: 35 },
  { value: 389, label: "Huyện Can Lộc", parent: 35 },
  { value: 390, label: "Huyện Hương Khê", parent: 35 },
  { value: 391, label: "Huyện Thạch Hà", parent: 35 },
  { value: 302, label: "Huyện Tiên Lữ", parent: 12 },
  { value: 393, label: "Huyện Kỳ Anh", parent: 35 },
  { value: 394, label: "Huyện Lộc Hà", parent: 35 },
  { value: 395, label: "Thị xã Kỳ Anh", parent: 35 },
  { value: 396, label: "Thành Phố Đồng Hới", parent: 40 },
  { value: 397, label: "Huyện Minh Hóa", parent: 40 },
  { value: 398, label: "Huyện Tuyên Hóa", parent: 40 },
  { value: 399, label: "Huyện Quảng Trạch", parent: 40 },
  { value: 400, label: "Huyện Bố Trạch", parent: 40 },
  { value: 401, label: "Huyện Quảng Ninh", parent: 40 },
  { value: 402, label: "Huyện Lệ Thủy", parent: 40 },
  { value: 403, label: "Thị xã Ba Đồn", parent: 40 },
  { value: 404, label: "Thành phố Đông Hà", parent: 43 },
  { value: 405, label: "Thị xã Quảng Trị", parent: 43 },
  { value: 406, label: "Huyện Vĩnh Linh", parent: 43 },
  { value: 407, label: "Huyện Hướng Hóa", parent: 43 },
  { value: 408, label: "Huyện Gio Linh", parent: 43 },
  { value: 409, label: "Huyện Đa Krông", parent: 43 },
  { value: 410, label: "Huyện Cam Lộ", parent: 43 },
  { value: 411, label: "Huyện Triệu Phong", parent: 43 },
  { value: 412, label: "Huyện Hải Lăng", parent: 43 },
  { value: 413, label: "Thành phố Huế", parent: 27 },
  { value: 414, label: "Huyện Phong Điền", parent: 27 },
  { value: 415, label: "Huyện Quảng Điền", parent: 27 },
  { value: 416, label: "Huyện Phú Vang", parent: 27 },
  { value: 417, label: "Thị xã Hương Thủy", parent: 27 },
  { value: 418, label: "Thị xã Hương Trà", parent: 27 },
  { value: 419, label: "Huyện A Lưới", parent: 27 },
  { value: 420, label: "Huyện Phú Lộc", parent: 27 },
  { value: 421, label: "Huyện Nam Đông", parent: 27 },
  { value: 422, label: "Quận Liên Chiểu", parent: 26 },
  { value: 423, label: "Quận Thanh Khê", parent: 26 },
  { value: 424, label: "Quận Hải Châu", parent: 26 },
  { value: 425, label: "Quận Sơn Trà", parent: 26 },
  { value: 426, label: "Quận Ngũ Hành Sơn", parent: 26 },
  { value: 332, label: "Huyện Hoa Lư", parent: 16 },
  { value: 428, label: "Huyện Hòa Vang", parent: 26 },
  { value: 429, label: "Thành phố Tam Kỳ", parent: 41 },
  { value: 430, label: "Thành phố Hội An", parent: 41 },
  { value: 431, label: "Huyện Tây Giang", parent: 41 },
  { value: 432, label: "Huyện Đông Giang", parent: 41 },
  { value: 433, label: "Huyện Đại Lộc", parent: 41 },
  { value: 434, label: "Thị xã Điện Bàn", parent: 41 },
  { value: 435, label: "Huyện Duy Xuyên", parent: 41 },
  { value: 436, label: "Huyện Quế Sơn", parent: 41 },
  { value: 437, label: "Huyện Nam Giang", parent: 41 },
  { value: 438, label: "Huyện Phước Sơn", parent: 41 },
  { value: 439, label: "Huyện Hiệp Đức", parent: 41 },
  { value: 440, label: "Huyện Thăng Bình", parent: 41 },
  { value: 441, label: "Huyện Tiên Phước", parent: 41 },
  { value: 442, label: "Huyện Bắc Trà My", parent: 41 },
  { value: 443, label: "Huyện Nam Trà My", parent: 41 },
  { value: 444, label: "Huyện Núi Thành", parent: 41 },
  { value: 445, label: "Huyện Phú Ninh", parent: 41 },
  { value: 446, label: "Huyện Nông Sơn", parent: 41 },
  { value: 447, label: "Thành phố Quảng Ngãi", parent: 42 },
  { value: 448, label: "Huyện Bình Sơn", parent: 42 },
  { value: 449, label: "Huyện Trà Bồng", parent: 42 },
  { value: 450, label: "Huyện Tây Trà", parent: 42 },
  { value: 451, label: "Huyện Sơn Tịnh", parent: 42 },
  { value: 452, label: "Huyện Tư Nghĩa", parent: 42 },
  { value: 453, label: "Huyện Sơn Hà", parent: 42 },
  { value: 454, label: "Huyện Sơn Tây", parent: 42 },
  { value: 455, label: "Huyện Minh Long", parent: 42 },
  { value: 456, label: "Huyện Nghĩa Hành", parent: 42 },
  { value: 457, label: "Huyện Mộ Đức", parent: 42 },
  { value: 458, label: "Thị xã Đức Phổ", parent: 42 },
  { value: 459, label: "Huyện Ba Tơ", parent: 42 },
  { value: 460, label: "Huyện Lý Sơn", parent: 42 },
  { value: 461, label: "Thành phố Quy Nhơn", parent: 30 },
  { value: 462, label: "Huyện Hoài Nhơn", parent: 30 },
  { value: 463, label: "Huyện Hoài Ân", parent: 30 },
  { value: 464, label: "Huyện Phù Mỹ", parent: 30 },
  { value: 465, label: "Huyện Vĩnh Thạnh", parent: 30 },
  { value: 466, label: "Huyện Tây Sơn", parent: 30 },
  { value: 467, label: "Huyện Phù Cát", parent: 30 },
  { value: 468, label: "Thị xã An Nhơn", parent: 30 },
  { value: 469, label: "Huyện Tuy Phước", parent: 30 },
  { value: 470, label: "Huyện Vân Canh", parent: 30 },
  { value: 471, label: "Thành phố Tuy Hoà", parent: 39 },
  { value: 472, label: "Thị xã Sông Cầu", parent: 39 },
  { value: 473, label: "Huyện Đồng Xuân", parent: 39 },
  { value: 474, label: "Huyện Tuy An", parent: 39 },
  { value: 475, label: "Huyện Sơn Hòa", parent: 39 },
  { value: 476, label: "Huyện Sông Hinh", parent: 39 },
  { value: 477, label: "Huyện Tây Hoà", parent: 39 },
  { value: 478, label: "Huyện Phú Hoà", parent: 39 },
  { value: 479, label: "Huyện Đông Hòa", parent: 39 },
  { value: 480, label: "Thành phố Nha Trang", parent: 28 },
  { value: 481, label: "Thành phố Cam Ranh", parent: 28 },
  { value: 482, label: "Huyện Cam Lâm", parent: 28 },
  { value: 483, label: "Huyện Vạn Ninh", parent: 28 },
  { value: 484, label: "Thị xã Ninh Hòa", parent: 28 },
  { value: 485, label: "Huyện Khánh Vĩnh", parent: 28 },
  { value: 486, label: "Huyện Diên Khánh", parent: 28 },
  { value: 487, label: "Huyện Khánh Sơn", parent: 28 },
  { value: 488, label: "Huyện Trường Sa", parent: 28 },
  { value: 489, label: "Thành phố Phan Rang-Tháp Chàm", parent: 38 },
  { value: 490, label: "Huyện Bác Ái", parent: 38 },
  { value: 392, label: "Huyện Cẩm Xuyên", parent: 35 },
  { value: 492, label: "Huyện Ninh Hải", parent: 38 },
  { value: 493, label: "Huyện Ninh Phước", parent: 38 },
  { value: 494, label: "Huyện Thuận Bắc", parent: 38 },
  { value: 495, label: "Huyện Thuận Nam", parent: 38 },
  { value: 496, label: "Thành phố Phan Thiết", parent: 31 },
  { value: 497, label: "Thị xã La Gi", parent: 31 },
  { value: 498, label: "Huyện Tuy Phong", parent: 31 },
  { value: 499, label: "Huyện Bắc Bình", parent: 31 },
  { value: 500, label: "Huyện Hàm Thuận Bắc", parent: 31 },
  { value: 501, label: "Huyện Hàm Thuận Nam", parent: 31 },
  { value: 502, label: "Huyện Tánh Linh", parent: 31 },
  { value: 503, label: "Huyện Đức Linh", parent: 31 },
  { value: 504, label: "Huyện Hàm Tân", parent: 31 },
  { value: 505, label: "Huyện Phú Quí", parent: 31 },
  { value: 506, label: "Thành phố Kon Tum", parent: 36 },
  { value: 507, label: "Huyện Đắk Glei", parent: 36 },
  { value: 508, label: "Huyện Ngọc Hồi", parent: 36 },
  { value: 509, label: "Huyện Đắk Tô", parent: 36 },
  { value: 510, label: "Huyện Kon Plông", parent: 36 },
  { value: 511, label: "Huyện Kon Rẫy", parent: 36 },
  { value: 512, label: "Huyện Đắk Hà", parent: 36 },
  { value: 513, label: "Huyện Sa Thầy", parent: 36 },
  { value: 514, label: "Huyện Tu Mơ Rông", parent: 36 },
  { value: 515, label: "Huyện Ia H' Drai", parent: 36 },
  { value: 516, label: "Thành phố Pleiku", parent: 34 },
  { value: 517, label: "Thị xã An Khê", parent: 34 },
  { value: 518, label: "Thị xã Ayun Pa", parent: 34 },
  { value: 519, label: "Huyện KBang", parent: 34 },
  { value: 520, label: "Huyện Đăk Đoa", parent: 34 },
  { value: 521, label: "Huyện Chư Păh", parent: 34 },
  { value: 522, label: "Huyện Ia Grai", parent: 34 },
  { value: 523, label: "Huyện Mang Yang", parent: 34 },
  { value: 524, label: "Huyện Kông Chro", parent: 34 },
  { value: 525, label: "Huyện Đức Cơ", parent: 34 },
  { value: 427, label: "Quận Cẩm Lệ", parent: 26 },
  { value: 527, label: "Huyện Chư Sê", parent: 34 },
  { value: 528, label: "Huyện Đăk Pơ", parent: 34 },
  { value: 529, label: "Huyện Ia Pa", parent: 34 },
  { value: 530, label: "Huyện Krông Pa", parent: 34 },
  { value: 531, label: "Huyện Phú Thiện", parent: 34 },
  { value: 532, label: "Huyện Chư Pưh", parent: 34 },
  { value: 533, label: "Thành phố Buôn Ma Thuột", parent: 32 },
  { value: 534, label: "Thị Xã Buôn Hồ", parent: 32 },
  { value: 535, label: "Huyện Ea H'leo", parent: 32 },
  { value: 536, label: "Huyện Ea Súp", parent: 32 },
  { value: 537, label: "Huyện Buôn Đôn", parent: 32 },
  { value: 538, label: "Huyện Cư M'gar", parent: 32 },
  { value: 539, label: "Huyện Krông Búk", parent: 32 },
  { value: 679, label: "Thành phố Vĩnh Long", parent: 63 },
  { value: 541, label: "Huyện Krông Năng", parent: 32 },
  { value: 542, label: "Huyện Ea Kar", parent: 32 },
  { value: 543, label: "Huyện M'Đrắk", parent: 32 },
  { value: 544, label: "Huyện Krông Bông", parent: 32 },
  { value: 545, label: "Huyện Krông Pắc", parent: 32 },
  { value: 546, label: "Huyện Krông A Na", parent: 32 },
  { value: 547, label: "Huyện Lắk", parent: 32 },
  { value: 548, label: "Huyện Cư Kuin", parent: 32 },
  { value: 549, label: "Thị xã Gia Nghĩa", parent: 33 },
  { value: 550, label: "Huyện Đăk Glong", parent: 33 },
  { value: 551, label: "Huyện Cư Jút", parent: 33 },
  { value: 552, label: "Huyện Đắk Mil", parent: 33 },
  { value: 553, label: "Huyện Krông Nô", parent: 33 },
  { value: 554, label: "Huyện Đắk Song", parent: 33 },
  { value: 555, label: "Huyện Đắk R'Lấp", parent: 33 },
  { value: 556, label: "Huyện Tuy Đức", parent: 33 },
  { value: 557, label: "Thành phố Đà Lạt", parent: 29 },
  { value: 558, label: "Thành phố Bảo Lộc", parent: 29 },
  { value: 559, label: "Huyện Đam Rông", parent: 29 },
  { value: 560, label: "Huyện Lạc Dương", parent: 29 },
  { value: 561, label: "Huyện Lâm Hà", parent: 29 },
  { value: 562, label: "Huyện Đơn Dương", parent: 29 },
  { value: 563, label: "Huyện Đức Trọng", parent: 29 },
  { value: 564, label: "Huyện Di Linh", parent: 29 },
  { value: 565, label: "Huyện Đạ Huoai", parent: 29 },
  { value: 566, label: "Huyện Đạ Tẻh", parent: 29 },
  { value: 567, label: "Huyện Cát Tiên", parent: 29 },
  { value: 568, label: "Thị xã Phước Long", parent: 51 },
  { value: 569, label: "Thị xã Đồng Xoài", parent: 51 },
  { value: 570, label: "Thị xã Bình Long", parent: 51 },
  { value: 571, label: "Huyện Bù Gia Mập", parent: 51 },
  { value: 572, label: "Huyện Lộc Ninh", parent: 51 },
  { value: 573, label: "Huyện Bù Đốp", parent: 51 },
  { value: 574, label: "Huyện Hớn Quản", parent: 51 },
  { value: 575, label: "Huyện Đồng Phú", parent: 51 },
  { value: 576, label: "Huyện Bù Đăng", parent: 51 },
  { value: 577, label: "Huyện Chơn Thành", parent: 51 },
  { value: 578, label: "Huyện Phú Riềng", parent: 51 },
  { value: 579, label: "Thành phố Tây Ninh", parent: 61 },
  { value: 580, label: "Huyện Tân Biên", parent: 61 },
  { value: 581, label: "Huyện Tân Châu", parent: 61 },
  { value: 582, label: "Huyện Dương Minh Châu", parent: 61 },
  { value: 583, label: "Huyện Châu Thành", parent: 61 },
  { value: 584, label: "Thị xã Hòa Thành", parent: 61 },
  { value: 585, label: "Huyện Gò Dầu", parent: 61 },
  { value: 586, label: "Huyện Bến Cầu", parent: 61 },
  { value: 587, label: "Thị xã Trảng Bàng", parent: 61 },
  { value: 588, label: "Thành phố Thủ Dầu Một", parent: 46 },
  { value: 589, label: "Huyện Bàu Bàng", parent: 46 },
  { value: 590, label: "Huyện Dầu Tiếng", parent: 46 },
  { value: 591, label: "Thị xã Bến Cát", parent: 46 },
  { value: 592, label: "Huyện Phú Giáo", parent: 46 },
  { value: 491, label: "Huyện Ninh Sơn", parent: 38 },
  { value: 594, label: "Thành phố Dĩ An", parent: 46 },
  { value: 595, label: "Thành phố Thuận An", parent: 46 },
  { value: 596, label: "Huyện Bắc Tân Uyên", parent: 46 },
  { value: 597, label: "Thành phố Biên Hòa", parent: 55 },
  { value: 598, label: "Thành phố Long Khánh", parent: 55 },
  { value: 599, label: "Huyện Tân Phú", parent: 55 },
  { value: 600, label: "Huyện Vĩnh Cửu", parent: 55 },
  { value: 601, label: "Huyện Định Quán", parent: 55 },
  { value: 602, label: "Huyện Trảng Bom", parent: 55 },
  { value: 603, label: "Huyện Thống Nhất", parent: 55 },
  { value: 604, label: "Huyện Cẩm Mỹ", parent: 55 },
  { value: 605, label: "Huyện Long Thành", parent: 55 },
  { value: 606, label: "Huyện Xuân Lộc", parent: 55 },
  { value: 607, label: "Huyện Nhơn Trạch", parent: 55 },
  { value: 608, label: "Thành phố Vũng Tàu", parent: 47 },
  { value: 609, label: "Thành phố Bà Rịa", parent: 47 },
  { value: 610, label: "Huyện Châu Đức", parent: 47 },
  { value: 611, label: "Huyện Xuyên Mộc", parent: 47 },
  { value: 612, label: "Huyện Long Điền", parent: 47 },
  { value: 613, label: "Huyện Đất Đỏ", parent: 47 },
  { value: 614, label: "Huyện Tân Thành", parent: 47 },
  { value: 615, label: "Quận 1", parent: 45 },
  { value: 616, label: "Quận 12", parent: 45 },
  { value: 617, label: "Thành phố Thủ Đức", parent: 45 },
  { value: 618, label: "Quận 9", parent: 45 },
  { value: 619, label: "Quận Gò Vấp", parent: 45 },
  { value: 620, label: "Quận Bình Thạnh", parent: 45 },
  { value: 621, label: "Quận Tân Bình", parent: 45 },
  { value: 622, label: "Quận Tân Phú", parent: 45 },
  { value: 623, label: "Quận Phú Nhuận", parent: 45 },
  { value: 624, label: "Quận 2", parent: 45 },
  { value: 625, label: "Quận 3", parent: 45 },
  { value: 626, label: "Quận 10", parent: 45 },
  { value: 627, label: "Quận 11", parent: 45 },
  { value: 628, label: "Quận 4", parent: 45 },
  { value: 629, label: "Quận 5", parent: 45 },
  { value: 630, label: "Quận 6", parent: 45 },
  { value: 631, label: "Quận 8", parent: 45 },
  { value: 526, label: "Huyện Chư Prông", parent: 34 },
  { value: 633, label: "Quận 7", parent: 45 },
  { value: 634, label: "Huyện Củ Chi", parent: 45 },
  { value: 635, label: "Huyện Hóc Môn", parent: 45 },
  { value: 636, label: "Huyện Bình Chánh", parent: 45 },
  { value: 637, label: "Huyện Nhà Bè", parent: 45 },
  { value: 638, label: "Huyện Cần Giờ", parent: 45 },
  { value: 639, label: "Thành phố Tân An", parent: 58 },
  { value: 640, label: "Thị xã Kiến Tường", parent: 58 },
  { value: 641, label: "Huyện Tân Hưng", parent: 58 },
  { value: 781, label: "Huyện Chợ Gạo", parent: 60 },
  { value: 643, label: "Huyện Mộc Hóa", parent: 58 },
  { value: 644, label: "Huyện Tân Thạnh", parent: 58 },
  { value: 645, label: "Huyện Thạnh Hóa", parent: 58 },
  { value: 646, label: "Huyện Đức Huệ", parent: 58 },
  { value: 647, label: "Huyện Đức Hòa", parent: 58 },
  { value: 648, label: "Huyện Bến Lức", parent: 58 },
  { value: 649, label: "Huyện Thủ Thừa", parent: 58 },
  { value: 650, label: "Huyện Tân Trụ", parent: 58 },
  { value: 651, label: "Huyện Cần Đước", parent: 58 },
  { value: 652, label: "Huyện Cần Giuộc", parent: 58 },
  { value: 653, label: "Thành phố Mỹ Tho", parent: 60 },
  { value: 654, label: "Thị xã Gò Công", parent: 60 },
  { value: 655, label: "Thị xã Cai Lậy", parent: 60 },
  { value: 656, label: "Huyện Tân Phước", parent: 60 },
  { value: 657, label: "Huyện Cái Bè", parent: 60 },
  { value: 658, label: "Huyện Cai Lậy", parent: 60 },
  { value: 772, label: "Huyện Châu Thành", parent: 52 },
  { value: 660, label: "Huyện Gò Công Tây", parent: 60 },
  { value: 661, label: "Huyện Gò Công Đông", parent: 60 },
  { value: 662, label: "Huyện Tân Phú Đông", parent: 60 },
  { value: 663, label: "Thành phố Bến Tre", parent: 52 },
  { value: 664, label: "Huyện Chợ Lách", parent: 52 },
  { value: 665, label: "Huyện Mỏ Cày Nam", parent: 52 },
  { value: 666, label: "Huyện Giồng Trôm", parent: 52 },
  { value: 667, label: "Huyện Bình Đại", parent: 52 },
  { value: 668, label: "Huyện Ba Tri", parent: 52 },
  { value: 669, label: "Huyện Thạnh Phú", parent: 52 },
  { value: 670, label: "Huyện Mỏ Cày Bắc", parent: 52 },
  { value: 671, label: "Thành phố Trà Vinh", parent: 62 },
  { value: 672, label: "Huyện Càng Long", parent: 62 },
  { value: 673, label: "Huyện Cầu Kè", parent: 62 },
  { value: 674, label: "Huyện Tiểu Cần", parent: 62 },
  { value: 675, label: "Huyện Cầu Ngang", parent: 62 },
  { value: 676, label: "Huyện Trà Cú", parent: 62 },
  { value: 677, label: "Huyện Duyên Hải", parent: 62 },
  { value: 678, label: "Thị xã Duyên Hải", parent: 62 },
  { value: 680, label: "Huyện Long Hồ", parent: 63 },
  { value: 681, label: "Huyện Mang Thít", parent: 63 },
  { value: 682, label: "Huyện Vũng Liêm", parent: 63 },
  { value: 683, label: "Huyện Tam Bình", parent: 63 },
  { value: 684, label: "Thị xã Bình Minh", parent: 63 },
  { value: 685, label: "Huyện Trà Ôn", parent: 63 },
  { value: 686, label: "Huyện Bình Tân", parent: 63 },
  { value: 687, label: "Thành phố Cao Lãnh", parent: 54 },
  { value: 689, label: "Thành phố Hồng Ngự", parent: 54 },
  { value: 690, label: "Huyện Tân Hồng", parent: 54 },
  { value: 691, label: "Huyện Hồng Ngự", parent: 54 },
  { value: 692, label: "Huyện Tháp Mười", parent: 54 },
  { value: 693, label: "Huyện Cao Lãnh", parent: 54 },
  { value: 694, label: "Huyện Thanh Bình", parent: 54 },
  { value: 695, label: "Huyện Lấp Vò", parent: 54 },
  { value: 696, label: "Huyện Lai Vung", parent: 54 },
  { value: 697, label: "Thành phố Long Xuyên", parent: 49 },
  { value: 698, label: "Thành phố Châu Đốc", parent: 49 },
  { value: 699, label: "Huyện An Phú", parent: 49 },
  { value: 700, label: "Thị xã Tân Châu", parent: 49 },
  { value: 701, label: "Huyện Phú Tân", parent: 49 },
  { value: 703, label: "Huyện Tịnh Biên", parent: 49 },
  { value: 593, label: "Thị xã Tân Uyên", parent: 46 },
  { value: 702, label: "Huyện Châu Phú", parent: 49 },
  { value: 706, label: "Thành phố Rạch Giá", parent: 57 },
  { value: 705, label: "Huyện Thoại Sơn", parent: 49 },
  { value: 707, label: "Thành phố Hà Tiên", parent: 57 },
  { value: 708, label: "Huyện Kiên Lương", parent: 57 },
  { value: 688, label: "Thành phố Sa Đéc", parent: 54 },
  { value: 709, label: "Huyện Hòn Đất", parent: 57 },
  { value: 717, label: "Huyện Phú Quốc", parent: 57 },
  { value: 711, label: "Huyện Tân Hiệp", parent: 57 },
  { value: 712, label: "Huyện Giồng Riềng", parent: 57 },
  { value: 713, label: "Huyện Gò Quao", parent: 57 },
  { value: 714, label: "Huyện An Biên", parent: 57 },
  { value: 715, label: "Huyện An Minh", parent: 57 },
  { value: 716, label: "Huyện Vĩnh Thuận", parent: 57 },
  { value: 718, label: "Huyện Kiên Hải", parent: 57 },
  { value: 719, label: "Huyện U Minh Thượng", parent: 57 },
  { value: 720, label: "Huyện Giang Thành", parent: 57 },
  { value: 721, label: "Quận Ninh Kiều", parent: 48 },
  { value: 722, label: "Quận Ô Môn", parent: 48 },
  { value: 723, label: "Quận Bình Thuỷ", parent: 48 },
  { value: 724, label: "Quận Cái Răng", parent: 48 },
  { value: 725, label: "Quận Thốt Nốt", parent: 48 },
  { value: 726, label: "Huyện Cờ Đỏ", parent: 48 },
  { value: 727, label: "Huyện Thới Lai", parent: 48 },
  { value: 728, label: "Thành phố Vị Thanh", parent: 56 },
  { value: 729, label: "Thành phố Ngã Bảy", parent: 56 },
  { value: 730, label: "Huyện Châu Thành A", parent: 56 },
  { value: 731, label: "Huyện Phụng Hiệp", parent: 56 },
  { value: 732, label: "Huyện Vị Thuỷ", parent: 56 },
  { value: 733, label: "Huyện Long Mỹ", parent: 56 },
  { value: 734, label: "Thị xã Long Mỹ", parent: 56 },
  { value: 735, label: "Thành phố Sóc Trăng", parent: 59 },
  { value: 736, label: "Huyện Kế Sách", parent: 59 },
  { value: 737, label: "Huyện Mỹ Tú", parent: 59 },
  { value: 738, label: "Huyện Cù Lao Dung", parent: 59 },
  { value: 739, label: "Huyện Long Phú", parent: 59 },
  { value: 740, label: "Huyện Mỹ Xuyên", parent: 59 },
  { value: 741, label: "Thị xã Ngã Năm", parent: 59 },
  { value: 742, label: "Huyện Thạnh Trị", parent: 59 },
  { value: 743, label: "Thị xã Vĩnh Châu", parent: 59 },
  { value: 744, label: "Huyện Trần Đề", parent: 59 },
  { value: 745, label: "Thành phố Bạc Liêu", parent: 50 },
  { value: 746, label: "Huyện Hồng Dân", parent: 50 },
  { value: 632, label: "Quận Bình Tân", parent: 45 },
  { value: 750, label: "Huyện Đông Hải", parent: 50 },
  { value: 752, label: "Thành phố Cà Mau", parent: 53 },
  { value: 753, label: "Huyện U Minh", parent: 53 },
  { value: 754, label: "Huyện Thới Bình", parent: 53 },
  { value: 755, label: "Huyện Trần Văn Thời", parent: 53 },
  { value: 756, label: "Huyện Cái Nước", parent: 53 },
  { value: 757, label: "Huyện Đầm Dơi", parent: 53 },
  { value: 758, label: "Huyện Năm Căn", parent: 53 },
  { value: 759, label: "Huyện Ngọc Hiển", parent: 53 },
  { value: 760, label: "Huyện Chợ Mới", parent: 49 },
  { value: 763, label: "Thành phố Cam Đường", parent: 13 },
  { value: 767, label: "Huyện Bảo Lâm", parent: 29 },
  { value: 769, label: "Huyện Châu Thành", parent: 58 },
  { value: 771, label: "Huyện Châu Thành", parent: 60 },
  { value: 780, label: "Thị xã Phú Mỹ", parent: 47 },
  { value: 775, label: "Huyện Châu Thành", parent: 62 },
  { value: 777, label: "Huyện Phong Điền", parent: 48 },
  { value: 782, label: "Thị xã Nghi Sơn", parent: 44 },
  { value: 783, label: "Huyện Châu Thành", parent: 57 },
  { value: 761, label: "Huyện Châu Thành", parent: 56 },
  { value: 764, label: "Huyện Châu Thành", parent: 54 },
  { value: 748, label: "Huyện Vĩnh Lợi", parent: 50 },
  { value: 749, label: "Thị xã Giá Rai", parent: 50 },
  { value: 751, label: "Huyện Hoà Bình", parent: 50 },
  { value: 766, label: "Huyện Bạch Long Vĩ", parent: 2 },
  { value: 765, label: "Huyện Tam Nông", parent: 54 },
  { value: 768, label: "Huyện Vĩnh Hưng", parent: 58 },
  { value: 762, label: "Huyện Châu Thành", parent: 49 },
  { value: 779, label: "Huyện Vĩnh Thạnh", parent: 48 },
  { value: 784, label: "Huyện Châu Thành", parent: 59 },
  { value: 785, label: "Huyện Phú Tân", parent: 53 },
  { value: 704, label: "Huyện Tri Tôn", parent: 49 },
  { value: 747, label: "Huyện Phước Long", parent: 50 },
];
export const renderDistrict = (id: any) => {
  const option = {
    66: "Quận Ba Đình ",
    67: "Quận Hoàn Kiếm ",
    68: "Quận Tây Hồ ",
    69: "Quận Long Biên ",
    70: "Quận Cầu Giấy ",
    71: "Quận Đống Đa ",
    72: "Quận Hai Bà Trưng ",
    73: "Quận Hoàng Mai ",
    74: "Quận Thanh Xuân ",
    75: "Huyện Sóc Sơn ",
    76: "Huyện Đông Anh ",
    77: "Huyện Gia Lâm ",
    78: "Quận Nam Từ Liêm ",
    79: "Huyện Thanh Trì ",
    80: "Quận Bắc Từ Liêm ",
    81: "Huyện Mê Linh ",
    82: "Quận Hà Đông ",
    83: "Thị xã Sơn Tây ",
    84: "Huyện Ba Vì ",
    85: "Huyện Phúc Thọ ",
    86: "Huyện Đan Phượng ",
    87: "Huyện Hoài Đức ",
    89: "Huyện Thạch Thất ",
    90: "Huyện Chương Mỹ ",
    91: "Huyện Thanh Oai ",
    92: "Huyện Thường Tín ",
    93: "Huyện Phú Xuyên ",
    94: "Huyện Ứng Hòa ",
    95: "Huyện Mỹ Đức ",
    96: "Thành phố Hà Giang ",
    97: "Huyện Đồng Văn ",
    98: "Huyện Mèo Vạc ",
    99: "Huyện Yên Minh ",
    100: "Huyện Quản Bạ ",
    101: "Huyện Vị Xuyên ",
    102: "Huyện Bắc Mê ",
    103: "Huyện Hoàng Su Phì ",
    104: "Huyện Xín Mần ",
    105: "Huyện Bắc Quang ",
    106: "Huyện Quang Bình ",
    107: "Thành phố Cao Bằng ",
    108: "Huyện Bảo Lâm ",
    109: "Huyện Bảo Lạc ",
    110: "Huyện Thông Nông ",
    111: "Huyện Hà Quảng ",
    112: "Huyện Trà Lĩnh ",
    113: "Huyện Trùng Khánh ",
    114: "Huyện Hạ Lang ",
    115: "Huyện Quảng Uyên ",
    116: "Huyện Phục Hoà ",
    117: "Huyện Hoà An ",
    118: "Huyện Nguyên Bình ",
    119: "Huyện Thạch An ",
    120: "Thành Phố Bắc Kạn ",
    121: "Huyện Pác Nặm ",
    122: "Huyện Ba Bể ",
    123: "Huyện Ngân Sơn ",
    124: "Huyện Bạch Thông ",
    125: "Huyện Chợ Đồn ",
    126: "Huyện Chợ Mới ",
    127: "Huyện Na Rì ",
    128: "Thành phố Tuyên Quang ",
    129: "Huyện Lâm Bình ",
    130: "Huyện Nà Hang ",
    131: "Huyện Chiêm Hóa ",
    132: "Huyện Hàm Yên ",
    133: "Huyện Yên Sơn ",
    134: "Huyện Sơn Dương ",
    135: "Thành phố Lào Cai ",
    136: "Huyện Bát Xát ",
    138: "Huyện Si Ma Cai ",
    139: "Huyện Bắc Hà ",
    140: "Huyện Bảo Thắng ",
    141: "Huyện Bảo Yên ",
    142: "Thị xã Sa Pa ",
    143: "Huyện Văn Bàn ",
    144: "Thành phố Điện Biên Phủ ",
    145: "Thị Xã Mường Lay ",
    146: "Huyện Mường Nhé ",
    147: "Huyện Mường Chà ",
    148: "Huyện Tủa Chùa ",
    149: "Huyện Tuần Giáo ",
    150: "Huyện Điện Biên ",
    151: "Huyện Điện Biên Đông ",
    152: "Huyện Mường Ảng ",
    153: "Huyện Nậm Pồ ",
    154: "Thành phố Lai Châu ",
    155: "Huyện Tam Đường ",
    156: "Huyện Mường Tè ",
    157: "Huyện Sìn Hồ ",
    158: "Huyện Phong Thổ ",
    159: "Huyện Than Uyên ",
    160: "Huyện Tân Uyên ",
    161: "Huyện Nậm Nhùn ",
    162: "Thành phố Sơn La ",
    88: "Huyện Quốc Oai ",
    164: "Huyện Thuận Châu ",
    165: "Huyện Mường La ",
    166: "Huyện Bắc Yên ",
    167: "Huyện Phù Yên ",
    168: "Huyện Mộc Châu ",
    169: "Huyện Yên Châu ",
    170: "Huyện Mai Sơn ",
    171: "Huyện Sông Mã ",
    172: "Huyện Sốp Cộp ",
    173: "Huyện Vân Hồ ",
    174: "Thành phố Yên Bái ",
    175: "Thị xã Nghĩa Lộ ",
    176: "Huyện Lục Yên ",
    177: "Huyện Văn Yên ",
    178: "Huyện Mù Căng Chải ",
    179: "Huyện Trấn Yên ",
    180: "Huyện Trạm Tấu ",
    181: "Huyện Văn Chấn ",
    182: "Huyện Yên Bình ",
    183: "Thành phố Hòa Bình ",
    184: "Huyện Đà Bắc ",
    185: "Huyện Kỳ Sơn ",
    186: "Huyện Lương Sơn ",
    187: "Huyện Kim Bôi ",
    188: "Huyện Cao Phong ",
    189: "Huyện Tân Lạc ",
    190: "Huyện Mai Châu ",
    191: "Huyện Lạc Sơn ",
    192: "Huyện Yên Thủy ",
    193: "Huyện Lạc Thủy ",
    194: "Thành phố Thái Nguyên ",
    195: "Thành phố Sông Công ",
    196: "Huyện Định Hóa ",
    197: "Huyện Phú Lương ",
    198: "Huyện Đồng Hỷ ",
    199: "Huyện Võ Nhai ",
    200: "Huyện Đại Từ ",
    201: "Thị xã Phổ Yên ",
    202: "Huyện Phú Bình ",
    203: "Thành phố Lạng Sơn ",
    204: "Huyện Tràng Định ",
    205: "Huyện Bình Gia ",
    206: "Huyện Văn Lãng ",
    207: "Huyện Cao Lộc ",
    208: "Huyện Văn Quan ",
    209: "Huyện Bắc Sơn ",
    210: "Huyện Hữu Lũng ",
    211: "Huyện Chi Lăng ",
    212: "Huyện Lộc Bình ",
    213: "Huyện Đình Lập ",
    214: "Thành phố Hạ Long ",
    215: "Thành phố Móng Cái ",
    137: "Huyện Mường Khương ",
    217: "Thành phố Uông Bí ",
    218: "Huyện Bình Liêu ",
    219: "Huyện Tiên Yên ",
    220: "Huyện Đầm Hà ",
    221: "Huyện Hải Hà ",
    222: "Huyện Ba Chẽ ",
    223: "Huyện Vân Đồn ",
    225: "Thị xã Đông Triều ",
    226: "Thị xã Quảng Yên ",
    227: "Huyện Cô Tô ",
    228: "Thành phố Bắc Giang ",
    229: "Huyện Yên Thế ",
    230: "Huyện Tân Yên ",
    231: "Huyện Lạng Giang ",
    232: "Huyện Lục Nam ",
    233: "Huyện Lục Ngạn ",
    234: "Huyện Sơn Động ",
    235: "Huyện Yên Dũng ",
    236: "Huyện Việt Yên ",
    237: "Huyện Hiệp Hòa ",
    238: "Thành phố Việt Trì ",
    239: "Thị xã Phú Thọ ",
    240: "Huyện Đoan Hùng ",
    241: "Huyện Hạ Hoà ",
    242: "Huyện Thanh Ba ",
    243: "Huyện Phù Ninh ",
    244: "Huyện Yên Lập ",
    163: "Huyện Quỳnh Nhai ",
    246: "Huyện Tam Nông ",
    247: "Huyện Lâm Thao ",
    248: "Huyện Thanh Sơn ",
    249: "Huyện Thanh Thuỷ ",
    250: "Huyện Tân Sơn ",
    251: "Thành phố Vĩnh Yên ",
    252: "Thành phố Phúc Yên ",
    253: "Huyện Lập Thạch ",
    254: "Huyện Tam Dương ",
    255: "Huyện Tam Đảo ",
    256: "Huyện Bình Xuyên ",
    257: "Huyện Yên Lạc ",
    258: "Huyện Vĩnh Tường ",
    259: "Huyện Sông Lô ",
    260: "Thành phố Bắc Ninh ",
    261: "Huyện Yên Phong ",
    262: "Huyện Quế Võ ",
    263: "Huyện Tiên Du ",
    264: "Thị xã Từ Sơn ",
    265: "Huyện Thuận Thành ",
    266: "Huyện Gia Bình ",
    267: "Huyện Lương Tài ",
    268: "Thành phố Hải Dương ",
    269: "Thành phố Chí Linh ",
    270: "Huyện Nam Sách ",
    271: "Huyện Kinh Môn ",
    272: "Huyện Kim Thành ",
    273: "Huyện Thanh Hà ",
    274: "Huyện Cẩm Giàng ",
    275: "Huyện Bình Giang ",
    276: "Huyện Gia Lộc ",
    277: "Huyện Tứ Kỳ ",
    278: "Huyện Ninh Giang ",
    279: "Huyện Thanh Miện ",
    280: "Quận Hồng Bàng ",
    281: "Quận Ngô Quyền ",
    282: "Quận Lê Chân ",
    283: "Quận Hải An ",
    284: "Quận Kiến An ",
    285: "Quận Đồ Sơn ",
    286: "Quận Dương Kinh ",
    287: "Huyện Thuỷ Nguyên ",
    288: "Huyện An Dương ",
    289: "Huyện An Lão ",
    290: "Huyện Kiến Thuỵ ",
    291: "Huyện Tiên Lãng ",
    292: "Huyện Vĩnh Bảo ",
    293: "Huyện Cát Hải ",
    294: "Thành phố Hưng Yên ",
    295: "Huyện Văn Lâm ",
    296: "Huyện Văn Giang ",
    297: "Huyện Yên Mỹ ",
    298: "Thị xã Mỹ Hào ",
    299: "Huyện Ân Thi ",
    300: "Huyện Khoái Châu ",
    301: "Huyện Kim Động ",
    216: "Thành phố Cẩm Phả ",
    303: "Huyện Phù Cừ ",
    304: "Thành phố Thái Bình ",
    305: "Huyện Quỳnh Phụ ",
    306: "Huyện Hưng Hà ",
    307: "Huyện Đông Hưng ",
    308: "Huyện Thái Thụy ",
    309: "Huyện Tiền Hải ",
    310: "Huyện Kiến Xương ",
    311: "Huyện Vũ Thư ",
    312: "Thành phố Phủ Lý ",
    313: "Thị xã Duy Tiên ",
    314: "Huyện Kim Bảng ",
    315: "Huyện Thanh Liêm ",
    316: "Huyện Bình Lục ",
    317: "Huyện Lý Nhân ",
    318: "Thành phố Nam Định ",
    319: "Huyện Mỹ Lộc ",
    320: "Huyện Vụ Bản ",
    321: "Huyện Ý Yên ",
    322: "Huyện Nghĩa Hưng ",
    323: "Huyện Nam Trực ",
    324: "Huyện Trực Ninh ",
    325: "Huyện Xuân Trường ",
    326: "Huyện Giao Thủy ",
    327: "Huyện Hải Hậu ",
    328: "Thành phố Ninh Bình ",
    329: "Thành phố Tam Điệp ",
    330: "Huyện Nho Quan ",
    331: "Huyện Gia Viễn ",
    245: "Huyện Cẩm Khê ",
    333: "Huyện Yên Khánh ",
    334: "Huyện Kim Sơn ",
    335: "Huyện Yên Mô ",
    336: "Thành phố Thanh Hóa ",
    337: "Thị xã Bỉm Sơn ",
    338: "Thành phố Sầm Sơn ",
    339: "Huyện Mường Lát ",
    340: "Huyện Quan Hóa ",
    341: "Huyện Bá Thước ",
    342: "Huyện Quan Sơn ",
    343: "Huyện Lang Chánh ",
    344: "Huyện Ngọc Lặc ",
    345: "Huyện Cẩm Thủy ",
    346: "Huyện Thạch Thành ",
    347: "Huyện Hà Trung ",
    348: "Huyện Vĩnh Lộc ",
    349: "Huyện Yên Định ",
    350: "Huyện Thọ Xuân ",
    351: "Huyện Thường Xuân ",
    352: "Huyện Triệu Sơn ",
    353: "Huyện Thiệu Hóa ",
    354: "Huyện Hoằng Hóa ",
    355: "Huyện Hậu Lộc ",
    356: "Huyện Nga Sơn ",
    357: "Huyện Như Xuân ",
    358: "Huyện Như Thanh ",
    359: "Huyện Nông Cống ",
    360: "Huyện Đông Sơn ",
    361: "Huyện Quảng Xương ",
    362: "Huyện Tĩnh Gia ",
    363: "Thành phố Vinh ",
    364: "Thị xã Cửa Lò ",
    365: "Thị xã Thái Hoà ",
    366: "Huyện Quế Phong ",
    367: "Huyện Quỳ Châu ",
    368: "Huyện Tương Dương ",
    369: "Huyện Nghĩa Đàn ",
    370: "Huyện Quỳ Hợp ",
    371: "Huyện Quỳnh Lưu ",
    372: "Huyện Con Cuông ",
    373: "Huyện Tân Kỳ ",
    374: "Huyện Anh Sơn ",
    375: "Huyện Diễn Châu ",
    376: "Huyện Yên Thành ",
    377: "Huyện Đô Lương ",
    378: "Huyện Thanh Chương ",
    379: "Huyện Nghi Lộc ",
    380: "Huyện Nam Đàn ",
    381: "Huyện Hưng Nguyên ",
    382: "Thị xã Hoàng Mai ",
    383: "Thành phố Hà Tĩnh ",
    384: "Thị xã Hồng Lĩnh ",
    385: "Huyện Hương Sơn ",
    386: "Huyện Đức Thọ ",
    387: "Huyện Vũ Quang ",
    388: "Huyện Nghi Xuân ",
    389: "Huyện Can Lộc ",
    390: "Huyện Hương Khê ",
    391: "Huyện Thạch Hà ",
    302: "Huyện Tiên Lữ ",
    393: "Huyện Kỳ Anh ",
    394: "Huyện Lộc Hà ",
    395: "Thị xã Kỳ Anh ",
    396: "Thành Phố Đồng Hới ",
    397: "Huyện Minh Hóa ",
    398: "Huyện Tuyên Hóa ",
    399: "Huyện Quảng Trạch ",
    400: "Huyện Bố Trạch ",
    401: "Huyện Quảng Ninh ",
    402: "Huyện Lệ Thủy ",
    403: "Thị xã Ba Đồn ",
    404: "Thành phố Đông Hà ",
    405: "Thị xã Quảng Trị ",
    406: "Huyện Vĩnh Linh ",
    407: "Huyện Hướng Hóa ",
    408: "Huyện Gio Linh ",
    409: "Huyện Đa Krông ",
    410: "Huyện Cam Lộ ",
    411: "Huyện Triệu Phong ",
    412: "Huyện Hải Lăng ",
    413: "Thành phố Huế ",
    414: "Huyện Phong Điền ",
    415: "Huyện Quảng Điền ",
    416: "Huyện Phú Vang ",
    417: "Thị xã Hương Thủy ",
    418: "Thị xã Hương Trà ",
    419: "Huyện A Lưới ",
    420: "Huyện Phú Lộc ",
    421: "Huyện Nam Đông ",
    422: "Quận Liên Chiểu ",
    423: "Quận Thanh Khê ",
    424: "Quận Hải Châu ",
    425: "Quận Sơn Trà ",
    426: "Quận Ngũ Hành Sơn ",
    332: "Huyện Hoa Lư ",
    428: "Huyện Hòa Vang ",
    429: "Thành phố Tam Kỳ ",
    430: "Thành phố Hội An ",
    431: "Huyện Tây Giang ",
    432: "Huyện Đông Giang ",
    433: "Huyện Đại Lộc ",
    434: "Thị xã Điện Bàn ",
    435: "Huyện Duy Xuyên ",
    436: "Huyện Quế Sơn ",
    437: "Huyện Nam Giang ",
    438: "Huyện Phước Sơn ",
    439: "Huyện Hiệp Đức ",
    440: "Huyện Thăng Bình ",
    441: "Huyện Tiên Phước ",
    442: "Huyện Bắc Trà My ",
    443: "Huyện Nam Trà My ",
    444: "Huyện Núi Thành ",
    445: "Huyện Phú Ninh ",
    446: "Huyện Nông Sơn ",
    447: "Thành phố Quảng Ngãi ",
    448: "Huyện Bình Sơn ",
    449: "Huyện Trà Bồng ",
    450: "Huyện Tây Trà ",
    451: "Huyện Sơn Tịnh ",
    452: "Huyện Tư Nghĩa ",
    453: "Huyện Sơn Hà ",
    454: "Huyện Sơn Tây ",
    455: "Huyện Minh Long ",
    456: "Huyện Nghĩa Hành ",
    457: "Huyện Mộ Đức ",
    458: "Thị xã Đức Phổ ",
    459: "Huyện Ba Tơ ",
    460: "Huyện Lý Sơn ",
    461: "Thành phố Quy Nhơn ",
    462: "Huyện Hoài Nhơn ",
    463: "Huyện Hoài Ân ",
    464: "Huyện Phù Mỹ ",
    465: "Huyện Vĩnh Thạnh ",
    466: "Huyện Tây Sơn ",
    467: "Huyện Phù Cát ",
    468: "Thị xã An Nhơn ",
    469: "Huyện Tuy Phước ",
    470: "Huyện Vân Canh ",
    471: "Thành phố Tuy Hoà ",
    472: "Thị xã Sông Cầu ",
    473: "Huyện Đồng Xuân ",
    474: "Huyện Tuy An ",
    475: "Huyện Sơn Hòa ",
    476: "Huyện Sông Hinh ",
    477: "Huyện Tây Hoà ",
    478: "Huyện Phú Hoà ",
    479: "Huyện Đông Hòa ",
    480: "Thành phố Nha Trang ",
    481: "Thành phố Cam Ranh ",
    482: "Huyện Cam Lâm ",
    483: "Huyện Vạn Ninh ",
    484: "Thị xã Ninh Hòa ",
    485: "Huyện Khánh Vĩnh ",
    486: "Huyện Diên Khánh ",
    487: "Huyện Khánh Sơn ",
    488: "Huyện Trường Sa ",
    489: "Thành phố Phan Rang-Tháp Chàm ",
    490: "Huyện Bác Ái ",
    392: "Huyện Cẩm Xuyên ",
    492: "Huyện Ninh Hải ",
    493: "Huyện Ninh Phước ",
    494: "Huyện Thuận Bắc ",
    495: "Huyện Thuận Nam ",
    496: "Thành phố Phan Thiết ",
    497: "Thị xã La Gi ",
    498: "Huyện Tuy Phong ",
    499: "Huyện Bắc Bình ",
    500: "Huyện Hàm Thuận Bắc ",
    501: "Huyện Hàm Thuận Nam ",
    502: "Huyện Tánh Linh ",
    503: "Huyện Đức Linh ",
    504: "Huyện Hàm Tân ",
    505: "Huyện Phú Quí ",
    506: "Thành phố Kon Tum ",
    507: "Huyện Đắk Glei ",
    508: "Huyện Ngọc Hồi ",
    509: "Huyện Đắk Tô ",
    510: "Huyện Kon Plông ",
    511: "Huyện Kon Rẫy ",
    512: "Huyện Đắk Hà ",
    513: "Huyện Sa Thầy ",
    514: "Huyện Tu Mơ Rông ",
    515: "Huyện Ia H' Drai ",
    516: "Thành phố Pleiku ",
    517: "Thị xã An Khê ",
    518: "Thị xã Ayun Pa ",
    519: "Huyện KBang ",
    520: "Huyện Đăk Đoa ",
    521: "Huyện Chư Păh ",
    522: "Huyện Ia Grai ",
    523: "Huyện Mang Yang ",
    524: "Huyện Kông Chro ",
    525: "Huyện Đức Cơ ",
    427: "Quận Cẩm Lệ ",
    527: "Huyện Chư Sê ",
    528: "Huyện Đăk Pơ ",
    529: "Huyện Ia Pa ",
    530: "Huyện Krông Pa ",
    531: "Huyện Phú Thiện ",
    532: "Huyện Chư Pưh ",
    533: "Thành phố Buôn Ma Thuột ",
    534: "Thị Xã Buôn Hồ ",
    535: "Huyện Ea H'leo ",
    536: "Huyện Ea Súp ",
    537: "Huyện Buôn Đôn ",
    538: "Huyện Cư M'gar ",
    539: "Huyện Krông Búk ",
    679: "Thành phố Vĩnh Long ",
    541: "Huyện Krông Năng ",
    542: "Huyện Ea Kar ",
    543: "Huyện M'Đrắk ",
    544: "Huyện Krông Bông ",
    545: "Huyện Krông Pắc ",
    546: "Huyện Krông A Na ",
    547: "Huyện Lắk ",
    548: "Huyện Cư Kuin ",
    549: "Thị xã Gia Nghĩa ",
    550: "Huyện Đăk Glong ",
    551: "Huyện Cư Jút ",
    552: "Huyện Đắk Mil ",
    553: "Huyện Krông Nô ",
    554: "Huyện Đắk Song ",
    555: "Huyện Đắk R'Lấp ",
    556: "Huyện Tuy Đức ",
    557: "Thành phố Đà Lạt ",
    558: "Thành phố Bảo Lộc ",
    559: "Huyện Đam Rông ",
    560: "Huyện Lạc Dương ",
    561: "Huyện Lâm Hà ",
    562: "Huyện Đơn Dương ",
    563: "Huyện Đức Trọng ",
    564: "Huyện Di Linh ",
    565: "Huyện Đạ Huoai ",
    566: "Huyện Đạ Tẻh ",
    567: "Huyện Cát Tiên ",
    568: "Thị xã Phước Long ",
    569: "Thị xã Đồng Xoài ",
    570: "Thị xã Bình Long ",
    571: "Huyện Bù Gia Mập ",
    572: "Huyện Lộc Ninh ",
    573: "Huyện Bù Đốp ",
    574: "Huyện Hớn Quản ",
    575: "Huyện Đồng Phú ",
    576: "Huyện Bù Đăng ",
    577: "Huyện Chơn Thành ",
    578: "Huyện Phú Riềng ",
    579: "Thành phố Tây Ninh ",
    580: "Huyện Tân Biên ",
    581: "Huyện Tân Châu ",
    582: "Huyện Dương Minh Châu ",
    583: "Huyện Châu Thành ",
    584: "Thị xã Hòa Thành ",
    585: "Huyện Gò Dầu ",
    586: "Huyện Bến Cầu ",
    587: "Thị xã Trảng Bàng ",
    588: "Thành phố Thủ Dầu Một ",
    589: "Huyện Bàu Bàng ",
    590: "Huyện Dầu Tiếng ",
    591: "Thị xã Bến Cát ",
    592: "Huyện Phú Giáo ",
    491: "Huyện Ninh Sơn ",
    594: "Thành phố Dĩ An ",
    595: "Thành phố Thuận An ",
    596: "Huyện Bắc Tân Uyên ",
    597: "Thành phố Biên Hòa ",
    598: "Thành phố Long Khánh ",
    599: "Huyện Tân Phú ",
    600: "Huyện Vĩnh Cửu ",
    601: "Huyện Định Quán ",
    602: "Huyện Trảng Bom ",
    603: "Huyện Thống Nhất ",
    604: "Huyện Cẩm Mỹ ",
    605: "Huyện Long Thành ",
    606: "Huyện Xuân Lộc ",
    607: "Huyện Nhơn Trạch ",
    608: "Thành phố Vũng Tàu ",
    609: "Thành phố Bà Rịa ",
    610: "Huyện Châu Đức ",
    611: "Huyện Xuyên Mộc ",
    612: "Huyện Long Điền ",
    613: "Huyện Đất Đỏ ",
    614: "Huyện Tân Thành ",
    615: "Quận 1 ",
    616: "Quận 12 ",
    617: "Thành phố Thủ Đức ",
    618: "Quận 9 ",
    619: "Quận Gò Vấp ",
    620: "Quận Bình Thạnh ",
    621: "Quận Tân Bình ",
    622: "Quận Tân Phú ",
    623: "Quận Phú Nhuận ",
    624: "Quận 2 ",
    625: "Quận 3 ",
    626: "Quận 10 ",
    627: "Quận 11 ",
    628: "Quận 4 ",
    629: "Quận 5 ",
    630: "Quận 6 ",
    631: "Quận 8 ",
    526: "Huyện Chư Prông ",
    633: "Quận 7 ",
    634: "Huyện Củ Chi ",
    635: "Huyện Hóc Môn ",
    636: "Huyện Bình Chánh ",
    637: "Huyện Nhà Bè ",
    638: "Huyện Cần Giờ ",
    639: "Thành phố Tân An ",
    640: "Thị xã Kiến Tường ",
    641: "Huyện Tân Hưng ",
    781: "Huyện Chợ Gạo ",
    643: "Huyện Mộc Hóa ",
    644: "Huyện Tân Thạnh ",
    645: "Huyện Thạnh Hóa ",
    646: "Huyện Đức Huệ ",
    647: "Huyện Đức Hòa ",
    648: "Huyện Bến Lức ",
    649: "Huyện Thủ Thừa ",
    650: "Huyện Tân Trụ ",
    651: "Huyện Cần Đước ",
    652: "Huyện Cần Giuộc ",
    653: "Thành phố Mỹ Tho ",
    654: "Thị xã Gò Công ",
    655: "Thị xã Cai Lậy ",
    656: "Huyện Tân Phước ",
    657: "Huyện Cái Bè ",
    658: "Huyện Cai Lậy ",
    772: "Huyện Châu Thành ",
    660: "Huyện Gò Công Tây ",
    661: "Huyện Gò Công Đông ",
    662: "Huyện Tân Phú Đông ",
    663: "Thành phố Bến Tre ",
    664: "Huyện Chợ Lách ",
    665: "Huyện Mỏ Cày Nam ",
    666: "Huyện Giồng Trôm ",
    667: "Huyện Bình Đại ",
    668: "Huyện Ba Tri ",
    669: "Huyện Thạnh Phú ",
    670: "Huyện Mỏ Cày Bắc ",
    671: "Thành phố Trà Vinh ",
    672: "Huyện Càng Long ",
    673: "Huyện Cầu Kè ",
    674: "Huyện Tiểu Cần ",
    675: "Huyện Cầu Ngang ",
    676: "Huyện Trà Cú ",
    677: "Huyện Duyên Hải ",
    678: "Thị xã Duyên Hải ",
    680: "Huyện Long Hồ ",
    681: "Huyện Mang Thít ",
    682: "Huyện Vũng Liêm ",
    683: "Huyện Tam Bình ",
    684: "Thị xã Bình Minh ",
    685: "Huyện Trà Ôn ",
    686: "Huyện Bình Tân ",
    687: "Thành phố Cao Lãnh ",
    689: "Thành phố Hồng Ngự ",
    690: "Huyện Tân Hồng ",
    691: "Huyện Hồng Ngự ",
    692: "Huyện Tháp Mười ",
    693: "Huyện Cao Lãnh ",
    694: "Huyện Thanh Bình ",
    695: "Huyện Lấp Vò ",
    696: "Huyện Lai Vung ",
    697: "Thành phố Long Xuyên ",
    698: "Thành phố Châu Đốc ",
    699: "Huyện An Phú ",
    700: "Thị xã Tân Châu ",
    701: "Huyện Phú Tân ",
    703: "Huyện Tịnh Biên ",
    593: "Thị xã Tân Uyên ",
    702: "Huyện Châu Phú ",
    706: "Thành phố Rạch Giá ",
    705: "Huyện Thoại Sơn ",
    707: "Thành phố Hà Tiên ",
    708: "Huyện Kiên Lương ",
    688: "Thành phố Sa Đéc ",
    709: "Huyện Hòn Đất ",
    717: "Huyện Phú Quốc ",
    711: "Huyện Tân Hiệp ",
    712: "Huyện Giồng Riềng ",
    713: "Huyện Gò Quao ",
    714: "Huyện An Biên ",
    715: "Huyện An Minh ",
    716: "Huyện Vĩnh Thuận ",
    718: "Huyện Kiên Hải ",
    719: "Huyện U Minh Thượng ",
    720: "Huyện Giang Thành ",
    721: "Quận Ninh Kiều ",
    722: "Quận Ô Môn ",
    723: "Quận Bình Thuỷ ",
    724: "Quận Cái Răng ",
    725: "Quận Thốt Nốt ",
    726: "Huyện Cờ Đỏ ",
    727: "Huyện Thới Lai ",
    728: "Thành phố Vị Thanh ",
    729: "Thành phố Ngã Bảy ",
    730: "Huyện Châu Thành A ",
    731: "Huyện Phụng Hiệp ",
    732: "Huyện Vị Thuỷ ",
    733: "Huyện Long Mỹ ",
    734: "Thị xã Long Mỹ ",
    735: "Thành phố Sóc Trăng ",
    736: "Huyện Kế Sách ",
    737: "Huyện Mỹ Tú ",
    738: "Huyện Cù Lao Dung ",
    739: "Huyện Long Phú ",
    740: "Huyện Mỹ Xuyên ",
    741: "Thị xã Ngã Năm ",
    742: "Huyện Thạnh Trị ",
    743: "Thị xã Vĩnh Châu ",
    744: "Huyện Trần Đề ",
    745: "Thành phố Bạc Liêu ",
    746: "Huyện Hồng Dân ",
    632: "Quận Bình Tân ",
    750: "Huyện Đông Hải ",
    752: "Thành phố Cà Mau ",
    753: "Huyện U Minh ",
    754: "Huyện Thới Bình ",
    755: "Huyện Trần Văn Thời ",
    756: "Huyện Cái Nước ",
    757: "Huyện Đầm Dơi ",
    758: "Huyện Năm Căn ",
    759: "Huyện Ngọc Hiển ",
    760: "Huyện Chợ Mới ",
    763: "Thành phố Cam Đường ",
    767: "Huyện Bảo Lâm ",
    769: "Huyện Châu Thành ",
    771: "Huyện Châu Thành ",
    780: "Thị xã Phú Mỹ ",
    775: "Huyện Châu Thành ",
    777: "Huyện Phong Điền ",
    782: "Thị xã Nghi Sơn ",
    783: "Huyện Châu Thành ",
    761: "Huyện Châu Thành ",
    764: "Huyện Châu Thành ",
    748: "Huyện Vĩnh Lợi ",
    749: "Thị xã Giá Rai ",
    751: "Huyện Hoà Bình ",
    766: "Huyện Bạch Long Vĩ ",
    765: "Huyện Tam Nông ",
    768: "Huyện Vĩnh Hưng ",
    762: "Huyện Châu Thành ",
    779: "Huyện Vĩnh Thạnh ",
    784: "Huyện Châu Thành ",
    785: "Huyện Phú Tân ",
    704: "Huyện Tri Tôn ",
    747: "Huyện Phước Long ",
  };
  if (!option[id]) {
    return "Không có dữ liệu";
  }
  return option[id];
};
